/datum/material_trait/silver_bane
	name = "Silver Bane"


/datum/material_trait/silver_bane/on_consume(mob/user, amount)
	if(ishuman(user))
		var/mob/living/carbon/human/H = user
		if(H.mind)
			var/datum/antagonist/vampirelord/V_lord = H.mind.has_antag_datum(/datum/antagonist/vampirelord/)
			var/datum/antagonist/werewolf/W = H.mind.has_antag_datum(/datum/antagonist/werewolf/)
			if(H.mind.has_antag_datum(/datum/antagonist/vampirelord/lesser))
				to_chat(H, span_userdanger("I've consumed silver, it is my BANE!"))
				H.Knockdown(10)
				H.Paralyze(10)
				H.adjustFireLoss(25)
				H.fire_act(1,10)
			if(V_lord)
				if(V_lord.vamplevel < 4 && !H.mind.has_antag_datum(/datum/antagonist/vampirelord/lesser))
					to_chat(H, span_userdanger("I've consumed silver, it is my BANE!"))
					H.Knockdown(10)
					H.Paralyze(10)
			if(W && W.transformed == TRUE)
				to_chat(H, span_userdanger("I've consumed silver, it is my BANE!"))
				H.Knockdown(10)
				H.Paralyze(10)
				H.adjustFireLoss(25)
				H.fire_act(1,10)

/datum/material_trait/silver_bane/on_life(mob/user)
	if(ishuman(user))
		var/mob/living/carbon/human/H = user
		if(H.mind)
			var/datum/antagonist/vampirelord/V_lord = H.mind.has_antag_datum(/datum/antagonist/vampirelord/)
			var/datum/antagonist/werewolf/W = H.mind.has_antag_datum(/datum/antagonist/werewolf/)
			if(H.mind.has_antag_datum(/datum/antagonist/vampirelord/lesser))
				to_chat(H, span_userdanger("I've consumed silver, it is my BANE!"))
				H.Knockdown(10)
				H.Paralyze(10)
				H.adjustFireLoss(25)
				H.fire_act(1,10)
			if(V_lord)
				if(V_lord.vamplevel < 4 && !H.mind.has_antag_datum(/datum/antagonist/vampirelord/lesser))
					to_chat(H, span_userdanger("I've consumed silver, it is my BANE!"))
					H.Knockdown(10)
					H.Paralyze(10)
			if(W && W.transformed == TRUE)
				to_chat(H, span_userdanger("I've consumed silver, it is my BANE!"))
				H.Knockdown(10)
				H.Paralyze(10)
				H.adjustFireLoss(25)
				H.fire_act(1,10)
