#define AB_CHECK_HANDS_BLOCKED (1<<0)
#define AB_CHECK_IMMOBILE (1<<1)
#define AB_CHECK_LYING (1<<2)
#define AB_CHECK_CONSCIOUS (1<<3)
#define AB_CHECK_INCAPACITATED (1<<4)

#define ACTION_BUTTON_DEFAULT_BACKGROUND "default"
