#define NO_MANA_POOL (1<<0)
#define MANA_POOL_FULL (1<<1)

#define MANA_POOL_TRANSFER_START (1<<2)
#define MANA_POOL_TRANSFER_STOP (1<<3)

#define MANA_POOL_ALREADY_TRANSFERRING (1<<4)
#define MANA_POOL_CANNOT_TRANSFER (1<<5)

#define MANA_POOL_TRANSFER_SKIP_ACTIVE (1<<6)

#define LEYLINE_BASE_RECHARGE 0.5 // Per second, we recharge this much man

#define MANA_CRYSTAL_BASE_HARDCAP 200
#define MANA_CRYSTAL_BASE_RECHARGE 0.001

#define BASE_MANA_CAPACITY 1000
#define MANA_CRYSTAL_BASE_MANA_CAPACITY (BASE_MANA_CAPACITY * 0.2)
#define CARBON_BASE_MANA_CAPACITY (BASE_MANA_CAPACITY)
#define LEYLINE_BASE_CAPACITY 600 //todo: standardize

#define BASE_MANA_SOFTCAP (BASE_MANA_CAPACITY * 0.2) //20 percent
#define BASE_MANA_CRYSTAL_SOFTCAP  MANA_CRYSTAL_BASE_MANA_CAPACITY
#define BASE_CARBON_MANA_SOFTCAP (CARBON_BASE_MANA_CAPACITY * 0.2)

#define BASE_MANA_OVERLOAD_THRESHOLD (BASE_MANA_CAPACITY * 0.9)
#define MANA_CRYSTAL_OVERLOAD_THRESHOLD MANA_CRYSTAL_BASE_MANA_CAPACITY
#define CARBON_MANA_OVERLOAD_THRESHOLD BASE_CARBON_MANA_SOFTCAP

#define BASE_MANA_OVERLOAD_COEFFICIENT 5
#define MANA_CRYSTAL_OVERLOAD_COEFFICIENT 0.1
#define CARBON_MANA_OVERLOAD_COEFFICIENT 5

#define MANA_OVERLOAD_DAMAGE_THRESHOLD 2
#define MANA_OVERLOAD_BASE_DAMAGE 10

// inverse - higher numbers decrease the intensity of the decay
#define BASE_MANA_EXPONENTIAL_DIVISOR 60 // careful with this value - low numbers will cause some fuckery
#define BASE_CARBON_MANA_EXPONENTIAL_DIVISOR (BASE_MANA_EXPONENTIAL_DIVISOR * 0.5)
#define MANA_CRYSTAL_BASE_DECAY_DIVISOR (BASE_MANA_EXPONENTIAL_DIVISOR * 5)

// in mana per second
#define BASE_MANA_DONATION_RATE (BASE_MANA_CAPACITY * 0.5)
#define BASE_MANA_CRYSTAL_DONATION_RATE (BASE_MANA_DONATION_RATE * 0.1)
#define BASE_LEYLINE_DONATION_RATE 30

#define MANA_BATTERY_MAX_TRANSFER_DISTANCE 3

#define MAGIC_MATERIAL_NAME "Primordial Quartz"
#define MAGIC_UNIT_OF_MEASUREMENT "Mana"
#define MAGIC_UNIT_OF_MAGNITUDE "TP" // Thaumatergic Potential
#define STORY_MAGIC_BASE_CONSUME_SCORE 50
#define THAUMATERGIC_SENSE_POOL_DISCERNMENT_LEVEL_ZERO 0
#define THAUMATERGIC_SENSE_POOL_DISCERNMENT_LEVEL_ONE 1
#define THAUMATERGIC_SENSE_POOL_DISCERNMENT_LEVEL_TWO 2

// MAGIC TRAITS GO HERE
// give this to an object to declare that its pool can be used during cast.
#define TRAIT_POOL_AVAILABLE_FOR_CAST "pool_available_for_cast"

#define COMSIG_MANA_POOL_INTRINSIC_RECHARGE_UPDATE "mana_pool_intrinsic_recharge_update"
#define COMSIG_ATOM_MANA_POOL_CHANGED "atom_mana_pool_changed"

#define MANA_ALL_LEYLINES (1<<1)
#define MANA_ALL_PYLONS (1<<2)
#define MANA_SOULS (1<<3)

#define MANA_DISPERSE_EVENLY 1
#define MANA_SEQUENTIAL 2

#define MANA_POOL_SKIP_NEXT_TRANSFER (1<<0)
#define MANA_POOL_INTRINSIC (1<<1)

#define COMSIG_SPELL_BEFORE_CAST "spell_before_cast"
#define COMSIG_SPELL_AFTER_CAST "spell_after_cast"

#define SPELL_MANA (1<<0)
#define SPELL_ESSENCE (1<<1)
