#define MAT_INGOT "Ingots"
#define MAT_STONE "Stone"
#define MAT_WOOD "Wood"
#define MAT_GEM "Gems"
#define MAT_ORE	"Ores"
#define MAT_COAL "Coal"
#define MAT_GRAIN "Grain"
#define MAT_VEG "Vegetable"
#define MAT_FRUIT "Fruit"
#define MAT_MEAT "Meat"

#define TASK_KEY_SPEED "speed"
#define TASK_KEY_REDUCTION "reduction"
#define TASK_KEY_QUANTITY "quantity"


#define WORKER_SLOT_HEAD "head"
#define WORKER_SLOT_PANTS "pants"
#define WORKER_SLOT_SHIRT "shirt"
#define WORKER_SLOT_SHOES "shoes"
#define WORKER_SLOT_HANDS "hands"
