#define DAMAGE_AXE 20
#define DAMAGE_AXE_WIELD 25
#define DAMAGE_HEAVYAXE_WIELD 30
#define DAMAGE_BAD_AXE 13
#define DAMAGE_BAD_AXE_WIELD 18

#define DAMAGE_WEAK_FLAIL 17
#define DAMAGE_NORMAL_FLAIL 23
#define DAMAGE_GOOD_FLAIL 28

#define DAMAGE_CLUB 15
#define DAMAGE_CLUB_WIELD 20
#define DAMAGE_MACE 20
#define DAMAGE_MACE_WIELD 25
#define DAMAGE_HEAVYCLUB_WIELD 30

#define DAMAGE_HAMMER 10
#define DAMAGE_HAMMER_WIELD 15

#define DAMAGE_KNIFE 10
#define DAMAGE_DAGGER 12

#define DAMAGE_STAFF 10
#define DAMAGE_STAFF_WIELD 15
#define DAMAGE_SPEAR 15
#define DAMAGE_SPEARPLUS 18
#define DAMAGE_SPEAR_WIELD 25
#define DAMAGE_HALBERD_WIELD 30

#define DAMAGE_SHORTSWORD 16
#define DAMAGE_SWORD 20
#define DAMAGE_SWORD_WIELD 25
#define DAMAGE_LONGSWORD_WIELD 28
#define DAMAGE_GREATSWORD_WIELD 30

#define DAMAGE_WHIP 20

// ===== AP DEFINES =======
#define AP_AXE_CUT 5
#define AP_AXE_CHOP 10
#define AP_HEAVYAXE_CHOP 25
#define AP_HEAVYAXE_STAB 35
#define AP_FLAIL_STRIKE 5
#define AP_CLUB_STRIKE 25
#define AP_CLUB_HEAVY_STRIKE 35
#define AP_FLAIL_SMASH 60
#define AP_CLUB_SMASH 30
#define AP_HEAVY_SMASH 40
#define AP_SPEAR_THRUST 20
#define AP_POLEARM_THRUST 40
#define AP_POLEARM_BASH 5
#define AP_POLEARM_CHOP 20
#define AP_GREATAXE_CHOP 20
#define AP_SWORD_THRUST 20
#define AP_SWORD_CHOP 5

//wdefense defines
#define TERRIBLE_PARRY -1
#define BAD_PARRY 0
#define MEDIOCRE_PARRY 1
#define AVERAGE_PARRY 2
#define GOOD_PARRY 3
#define GREAT_PARRY 4
#define ULTMATE_PARRY 5

//wbalance defines
#define VERY_EASY_TO_DODGE -2
#define EASY_TO_DODGE -1
#define DODGE_CHANCE_NORMAL 0
#define HARD_TO_DODGE 1
#define VERY_HARD_TO_DODGE 2
