#define IRON_MULTIPLIER 1
#define STEEL_MULTIPLIER 1

#define COPPER_MULTIPLIER 1.14
#define BRONZE_MULTIPLIER 1.13
#define TIN_MULTIPLIER 0.9

#define GOLD_MULITPLIER 1.4
#define SILVER_MULTIPLIER 1.3

#define BLACKSTEEL_MULTIPLIER 0.8
